name: gds
on: [push, workflow_dispatch]
jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp26b
        with:
          pdk: ihp-sg13g2
          tools-ref: 01d5d2814fa9dd61e9d211e0b235a4a592a9316a
          librelane-version: '3.0.5'
  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttihp26b
  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Gate-level test
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp26b
  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttihp26b
